dist: xenial
language: python
cache: pip
python:
  - '3.7'
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq stockfish
before_script:
  - export PATH=$PATH:/usr/games/
script:
  - python setup.py test
notifications:
  email:
    - zhelyabuzhsky@icloud.com
